{...}: {
  home.file.".blerc".text = ''
    ble-face argument_error=fg=red,bold
    ble-face argument_option=fg=cyan
    ble-face auto_complete=fg=245
    ble-face cmdinfo_cd_cdpath=fg=blue
    ble-face command_alias=fg=cyan
    ble-face command_builtin=fg=green
    ble-face command_builtin_dot=fg=green
    ble-face command_directory=fg=blue,underline
    ble-face command_file=fg=green
    ble-face command_function=fg=magenta
    ble-face command_jobs=fg=yellow,bold
    ble-face command_keyword=fg=green
    ble-face disabled=fg=244
    ble-face filename_block=fg=red,bold
    ble-face filename_character=fg=yellow,bold
    ble-face filename_directory=fg=blue,underline
    ble-face filename_directory_sticky=fg=white,bg=blue
    ble-face filename_executable=fg=green,underline
    ble-face filename_link=fg=cyan,underline
    ble-face filename_ls_colors=underline
    ble-face filename_orphan=fg=magenta,bold
    ble-face filename_other=fg=252
    ble-face filename_pipe=fg=yellow,bold
    ble-face filename_setgid=fg=black,bg=green
    ble-face filename_setuid=fg=black,bg=red
    ble-face filename_socket=fg=magenta,bold
    ble-face filename_url=fg=blue,underline
    ble-face filename_warning=fg=red,bold
    ble-face overwrite_mode=fg=white,bg=red
    ble-face prompt_status_line=fg=white,bg=blue
    ble-face region=fg=black,bg=yellow
    ble-face region_insert=fg=black,bg=114
    ble-face region_match=fg=black,bg=green
    ble-face region_target=fg=black,bg=cyan
    ble-face syntax_brace=fg=blue
    ble-face syntax_command=fg=green
    ble-face syntax_comment=fg=242
    ble-face syntax_default=fg=252
    ble-face syntax_delimiter=fg=252
    ble-face syntax_document=fg=cyan
    ble-face syntax_document_begin=fg=cyan,bold
    ble-face syntax_error=fg=red,bold
    ble-face syntax_escape=fg=magenta,bold
    ble-face syntax_expr=fg=blue
    ble-face syntax_function_name=fg=magenta,bold
    ble-face syntax_glob=fg=red,bold
    ble-face syntax_history_expansion=fg=red,bold
    ble-face syntax_param_expansion=fg=cyan
    ble-face syntax_quotation=fg=green
    ble-face syntax_quoted=fg=green
    ble-face syntax_tilde=fg=blue
    ble-face syntax_varname=fg=magenta
    ble-face varname_array=fg=magenta,bold
    ble-face varname_empty=fg=red
    ble-face varname_export=fg=green,bold
    ble-face varname_expr=fg=magenta,bold
    ble-face varname_hash=fg=cyan,bold
    ble-face varname_number=fg=red
    ble-face varname_readonly=fg=green
    ble-face varname_transform=fg=blue,bold
    ble-face varname_unset=fg=red
    ble-face vbell=reverse
    ble-face vbell_erase=bg=239
    ble-face vbell_flash=fg=black,bg=green
  '';
}
