#!/usr/bin/env bash

# Lists all users defined
# in current configuration

set -euo pipefail

cd "$(dirname "$0")"

script='
    { config, lib, ...}:
        lib.escapeShellArgs
            (builtins.attrNames config.cfgLib.users)'

users="$(nix eval .#nixosConfigurations.default --apply "$script" --raw)"

echo "$users" | xargs echo -n
