#!/usr/bin/env bash

set -euo pipefail

# Actually rebuild system
rebuild() {
    sudo nixos-rebuild switch --flake .#default --verbose
}

# activate a single user "$1"
activate_user() {
    local user="$1"

    echo "-------------------- activate $user --------------------"

    local gen
    gen="$(awk '/ExecStart=/ { print $2; }' /etc/systemd/system/home-manager-"$user".service)"

    rm -f "/home/$user/.config/fcitx5/profile"
    rm -f "/home/$user/.config/fcitx5/config"

    sudo -u "$user" "$gen/activate"
}

# Call activations scripts for all users
activate_all() {
    local users
    users=($(./lsusers))

    for user in "${users[@]}"; do
        activate_user "$user"
    done
}

run() {
    cd "$(dirname "$0")"
    rebuild
    activate_all
}

run
