{lib, ...}: let
  attrsOfNamed = type:
    lib.types.addCheck
    (lib.types.attrsOf type)
    # check won't work for whatever reason
    (
      users:
        builtins.all
        (x: x)
        (
          lib.attrsets.mapAttrsToList
          (name: user: user.name == name)
          users
        )
    );

  moduleOpt = type:
    lib.types.unique
    {
      message =
        "this option is generated by module, "
        + "it should not be defined manualy";
    }
    type;

  exactStr = s:
    with lib.types;
      addCheck
      str
      (type: type == s);

  isOfType = type: var:
    (builtins.hasAttr "type" var)
    && var.type == type;
in {
  config = {
    _cfgLib = {
      inherit
        moduleOpt
        attrsOfNamed
        isOfType
        exactStr
        ;
    };
  };
}
