[general]
import = [
    "theme.toml"
]

[font]
size = 11.0

[keyboard]
bindings = [
	{ mods = "Control|Shift", key = "Return", action = "SpawnNewInstance" },
    { mods = "Control|Shift", key = "n",      command = "/home/kotfind/.config/alacritty/toggle_theme.sh" }
]

[window]
padding = { x = 2, y = 2 }
