common:
  sample: ENC[AES256_GCM,data:QlvyldsFu68nYMG7YQ==,iv:Fkx9v0Aje5XfOQmGowrMnI+uWIwJi03u8Tmv8fqF3N4=,tag:tBbPJk+KI3mVv9GZjqN0pw==,type:str]
sops:
  age:
    - recipient: age1aj2l0lkpe4lxuu3l5esv3k74lhrxffg2znzv7gj3ddtqchrdsa3qgzzuy6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOHNaK3ZlZ2JaUEpvM1do
        enFITHRIT2JBWFNHRkF4WnI5TVZVbE9TaGhnCk4vcHI4NXFHVDZVbjFxVHRjcHdv
        d3lBVkJsdnc4ZjdSOU9WWGd0MkpVSmMKLS0tIFE5QndyQXZKTDJieE12MzUwVDBK
        akttTWlZa0V2T0hsaU9XOHNNWFBwRUEKVA8RiguFmchmEej2ttpqQ+JZwuiCgC89
        HT/izA/0k3NZswzDiWRdjf0R/zmrsQNJBr/qks/YAxeKXBta7fHjag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T08:23:50Z"
  mac: ENC[AES256_GCM,data:pqQDu5dSEWAXZWbzwMpy5sT9xzQD2cz0rjibDJjEuHhSKPiwG3CEKsyAHnioZdXAn9UOyqmb5rtU5qnTvBbpsBNviBzDSWiHuq3bTJV/3Kk12dVn2V1iYdlEPqRUi4JKedXIWPrYNqUw8ENsN0e9s9BhamdzUomj6NmXQ0m3XTA=,iv:ecViGvu/olMgkGG191gneJpZsZM2n1eNwnd4gmp7oFU=,tag:x/N/E9cZX43r3mq4tOALIg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
