common:
  mihomo:
    secret: ENC[AES256_GCM,data:032Hkn/SM4IWegTbrXyG97I=,iv:riqRPfbVR+CN2dPes91sZdfKHiYqc6Js5j28iIFhoG8=,tag:20WgYB2vnAp6Mn9cP1leDA==,type:str]
    providers:
      "1":
        name: ENC[AES256_GCM,data:WJroGS8IY+fACgcOaiBx3us=,iv:03QltVa9F9/I8dMLWPsspLEf297RPP92g5o0A9+hJQU=,tag:zo7FeLy/m8SeVX75oRrlNA==,type:str]
        url: ENC[AES256_GCM,data:Y2tg1RF+KIlbGKDuh+EUjzzp6chhpqWa5bjgen0ymefnvbCbUHqE4mLkZ9NVtXCyKtVkSpy2gurTsT/JmlNoluaT53JLNfA+cMcMqhwi,iv:UOJn6aWzWpZjt2F9M1PXfeghR/2Ucqa6p62NQdhI+9I=,tag:FM0LvcT9tmO1D2pd9i8NkA==,type:str]
      "2":
        name: ENC[AES256_GCM,data:FOhVkDwEZQCBNqM07gDBeyIMrI4=,iv:hmtqOxdcJev0JPQeRS7rFIyOfgxxvhqJ+6jc6nlMcuo=,tag:FTObhKNPLY78hFjjSpAbhw==,type:str]
        url: ENC[AES256_GCM,data:ZYAx3JqEbniZpYO84oP+ZRoCCetxsrW2NG3bWcNu8WGTsrLP9FATfqgljKDlaNTSHFMLYGNc/aLYHDQfoLYDii0CHXXdaQCUpRFHRXQnXjKVYH0PZU6s16p/AEJu6gA6AOJQMfp3tZ8We6X7Z8ZopKLn,iv:jcZpGm1yj1ZLR30fLcOIVF4V3/2dcE95/ACaOQcR/GM=,tag:eYj03uV53DBxdk7knGglTQ==,type:str]
    groups:
      "1":
        name: ENC[AES256_GCM,data:Q/mk6Xk050Q8mz3IHj8=,iv:6uR9wo7AZL+QQ9Xq3WWLKhL9l8OEiSFI/F/s7ccpU+4=,tag:YDHUhHyS5RDy+DWAdtmVGw==,type:str]
      "2":
        name: ENC[AES256_GCM,data:/G2YIpYIWv2Fn8gIlYky80U=,iv:vLcqbLAFtcbrnSSdAawME/AHDzfkHw84gXA+y+oncWo=,tag:8wp8U8cuSkElhtRfwVgu7Q==,type:str]
sops:
  age:
    - recipient: age1aj2l0lkpe4lxuu3l5esv3k74lhrxffg2znzv7gj3ddtqchrdsa3qgzzuy6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOHNaK3ZlZ2JaUEpvM1do
        enFITHRIT2JBWFNHRkF4WnI5TVZVbE9TaGhnCk4vcHI4NXFHVDZVbjFxVHRjcHdv
        d3lBVkJsdnc4ZjdSOU9WWGd0MkpVSmMKLS0tIFE5QndyQXZKTDJieE12MzUwVDBK
        akttTWlZa0V2T0hsaU9XOHNNWFBwRUEKVA8RiguFmchmEej2ttpqQ+JZwuiCgC89
        HT/izA/0k3NZswzDiWRdjf0R/zmrsQNJBr/qks/YAxeKXBta7fHjag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T10:14:37Z"
  mac: ENC[AES256_GCM,data:cXNRdPRfdQCdbqo/s5FkTD34Bcpl4iS1OQyxhr6lAnWbd26TBZJ+BX10LxtMUED/9k0SqLn6+gpDtpW/TJrOGkh9jh8LcOxG8exygm3MqZEheMMzdQEc1hpYccEHI4GAcmmzNAZ6Yj3gB2FBD2YYdLIuUGm1JtPZ17J6uXLqo2I=,iv:8v7r9wDnDBEYzRdWl1vQYUKgab4HGhXHqbPcPzcbvUw=,tag:IRhoKzDuJwAry3h6cPF8UQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
