kotfindPC-ip-address: ENC[AES256_GCM,data:zHLScCj4Iz5evqaY,iv:6ekVRiDP0XhQ9oBIkilf5pEeZ4RlbJGVdDPeYsQpEJU=,tag:roQVr3AnygXuT7qzkLAtXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aj2l0lkpe4lxuu3l5esv3k74lhrxffg2znzv7gj3ddtqchrdsa3qgzzuy6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZk91VUlTT3JWcDhVNWhM
            Z0VTRzZQR2RrTGI0b1pQYzVZU2VScTFaOVFvCnV5MFFDeG5JNm5aWVhOekMyNTJ4
            Z0VpZjhvUUdXMi9PRHNuVU5qMnJrM3cKLS0tIENCenB1YkY1cUluc3A3L2lFMXBL
            MFVlUmxqY0dhdjdKa3Y4NVRSZkVWMFUKA9YpXFw3g3VnSfWi7v20QbCP+ORVe620
            Tgk2GWbNidkm6UE0fbRzdVaoVohUcanmsvGuA6hH6fkXfb8m++7Hwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-22T18:39:08Z"
    mac: ENC[AES256_GCM,data:qWkauaL3qAz64Qn6Lyd+EH9AFz8HJxV/7Z+y3K8oIiDuOF8HpzrZpMdQet2iHmlenzr8op2AqyTHfObPM6Zivej+FRO61CnkIyNFq7fKWd6Lt54P+gggfIbt+rlN84V+Ho5AdUtLsK2klME6BfNx64oJ6/uNT7oSKU4IDRnDnRg=,iv:CoL7R/9ODSr7itudMuz7mDgqp+oYpwcM1UE8JpAf2wQ=,tag:O5kgxJkTgHxaS/tcRNj+kA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
