{config, ...}: let
  homeDir = config.home.homeDirectory;
in {
  programs.claude-code.settings.permissions = {
    disableAutoMode = "disable";
    disableBypassPermissionsMode = "disable";

    allow = [
      "Read"
      "Bash(git log:*)"
      "Bash(git diff:*)"
      "Bash(git status:*)"
      "Bash(git show:*)"
      "Bash(cargo build:*)"
      "Bash(cargo check:*)"
      "Bash(cargo clippy:*)"
      "Bash(cargo fmt:*)"
      "Bash(eza:*)"
      "Bash(fd:*)"
      "Bash(rg:*)"
      "Bash(nix build:*)"
      "Bash(nix eval:*)"
      "Bash(nix flake check:*)"
      "Bash(nix search:*)"
      "Bash(nix-locate:*)"
      "Bash(nix-instantiate:*)"
      "Bash(man:*)"
      "Bash(readelf:*)"
      "Bash(gh browse:*)"
      "Bash(gh cache list:*)"
      "Bash(gh completion:*)"
      "Bash(gh config get:*)"
      "Bash(gh config list:*)"
      "Bash(gh extension list:*)"
      "Bash(gh gist list:*)"
      "Bash(gh gist view:*)"
      "Bash(gh help:*)"
      "Bash(gh issue list:*)"
      "Bash(gh issue status:*)"
      "Bash(gh issue view:*)"
      "Bash(gh label list:*)"
      "Bash(gh org list:*)"
      "Bash(gh pr checks:*)"
      "Bash(gh pr diff:*)"
      "Bash(gh pr list:*)"
      "Bash(gh pr status:*)"
      "Bash(gh pr view:*)"
      "Bash(gh release list:*)"
      "Bash(gh release view:*)"
      "Bash(gh repo clone:*)"
      "Bash(gh repo list:*)"
      "Bash(gh repo view:*)"
      "Bash(gh run list:*)"
      "Bash(gh run view:*)"
      "Bash(gh search:*)"
      "Bash(gh secret list:*)"
      "Bash(gh status:*)"
      "Bash(gh variable list:*)"
      "Bash(gh version:*)"
      "Bash(gh workflow list:*)"
      "Bash(gh workflow view:*)"
      "WebSearch"
      "WebFetch"
    ];
    additionalDirectories = [
      "/etc/nixos"
      "${homeDir}/nixos"
      "${homeDir}/.cargo/registry/cache"
      "${homeDir}/.cargo/registry/index"
      "${homeDir}/.cargo/registry/src"
    ];
  };
}
