{config, ...}: let
  homeDir = config.home.homeDirectory;
in {
  programs.claude-code.settings.permissions = {
    defaultMode = "auto";
    disableBypassPermissionsMode = "disable";

    ask = [
      "Bash(git commit:*)"
      "Bash(git rebase:*)"
      "Bash(git reset:*)"
      "Bash(git cherry-pick:*)"
      "Bash(git revert:*)"
      "Bash(git merge:*)"
      "Bash(git am:*)"
      "Bash(git pull:*)"
      "Bash(git push*--force*)"
      "Bash(git push* -f*)"
      "Bash(git filter-branch:*)"
      "Bash(git filter-repo:*)"
      "Bash(git replace:*)"
      "Bash(git update-ref:*)"
      "Bash(gh alias set:*)"
      "Bash(gh auth login:*)"
      "Bash(gh auth logout:*)"
      "Bash(gh auth refresh:*)"
      "Bash(gh auth switch:*)"
      "Bash(gh cache delete:*)"
      "Bash(gh codespace create:*)"
      "Bash(gh codespace delete:*)"
      "Bash(gh codespace edit:*)"
      "Bash(gh config set:*)"
      "Bash(gh extension install:*)"
      "Bash(gh extension remove:*)"
      "Bash(gh gist create:*)"
      "Bash(gh gist delete:*)"
      "Bash(gh gist edit:*)"
      "Bash(gh gpg-key add:*)"
      "Bash(gh issue close:*)"
      "Bash(gh issue comment:*)"
      "Bash(gh issue create:*)"
      "Bash(gh issue delete:*)"
      "Bash(gh issue edit:*)"
      "Bash(gh issue lock:*)"
      "Bash(gh issue reopen:*)"
      "Bash(gh issue transfer:*)"
      "Bash(gh issue unlock:*)"
      "Bash(gh label create:*)"
      "Bash(gh label delete:*)"
      "Bash(gh label edit:*)"
      "Bash(gh pr close:*)"
      "Bash(gh pr comment:*)"
      "Bash(gh pr create:*)"
      "Bash(gh pr edit:*)"
      "Bash(gh pr merge:*)"
      "Bash(gh pr ready:*)"
      "Bash(gh pr reopen:*)"
      "Bash(gh pr review:*)"
      "Bash(gh release create:*)"
      "Bash(gh release delete:*)"
      "Bash(gh release edit:*)"
      "Bash(gh release upload:*)"
      "Bash(gh repo archive:*)"
      "Bash(gh repo create:*)"
      "Bash(gh repo delete:*)"
      "Bash(gh repo edit:*)"
      "Bash(gh repo fork:*)"
      "Bash(gh repo rename:*)"
      "Bash(gh repo set-default:*)"
      "Bash(gh repo sync:*)"
      "Bash(gh ruleset create:*)"
      "Bash(gh ruleset delete:*)"
      "Bash(gh ruleset edit:*)"
      "Bash(gh run cancel:*)"
      "Bash(gh run delete:*)"
      "Bash(gh run rerun:*)"
      "Bash(gh secret delete:*)"
      "Bash(gh secret set:*)"
      "Bash(gh ssh-key add:*)"
      "Bash(gh variable delete:*)"
      "Bash(gh variable set:*)"
      "Bash(gh workflow disable:*)"
      "Bash(gh workflow enable:*)"
      "Bash(gh workflow run:*)"
      "Bash(sops:*)"
    ];

    allow = [
      "Read"
      "Bash(git log:*)"
      "Bash(git diff:*)"
      "Bash(git status:*)"
      "Bash(git show:*)"
      "Bash(cargo build:*)"
      "Bash(cargo check:*)"
      "Bash(cargo clippy:*)"
      "Bash(cargo fmt:*)"
      "Bash(eza:*)"
      "Bash(fd:*)"
      "Bash(rg:*)"
      "Bash(nix build:*)"
      "Bash(nix eval:*)"
      "Bash(nix flake check:*)"
      "Bash(nix search:*)"
      "Bash(nix-locate:*)"
      "Bash(nix-instantiate:*)"
      "Bash(man:*)"
      "Bash(readelf:*)"
      "Bash(gh browse:*)"
      "Bash(gh cache list:*)"
      "Bash(gh completion:*)"
      "Bash(gh config get:*)"
      "Bash(gh config list:*)"
      "Bash(gh extension list:*)"
      "Bash(gh gist list:*)"
      "Bash(gh gist view:*)"
      "Bash(gh help:*)"
      "Bash(gh issue list:*)"
      "Bash(gh issue status:*)"
      "Bash(gh issue view:*)"
      "Bash(gh label list:*)"
      "Bash(gh org list:*)"
      "Bash(gh pr checks:*)"
      "Bash(gh pr diff:*)"
      "Bash(gh pr list:*)"
      "Bash(gh pr status:*)"
      "Bash(gh pr view:*)"
      "Bash(gh release list:*)"
      "Bash(gh release view:*)"
      "Bash(gh repo clone:*)"
      "Bash(gh repo list:*)"
      "Bash(gh repo view:*)"
      "Bash(gh run list:*)"
      "Bash(gh run view:*)"
      "Bash(gh search:*)"
      "Bash(gh secret list:*)"
      "Bash(gh status:*)"
      "Bash(gh variable list:*)"
      "Bash(gh version:*)"
      "Bash(gh workflow list:*)"
      "Bash(gh workflow view:*)"
      "WebSearch"
      "WebFetch"
    ];
    additionalDirectories = [
      "/etc/nixos"
      "${homeDir}/nixos"
      "${homeDir}/.cargo/registry/cache"
      "${homeDir}/.cargo/registry/index"
      "${homeDir}/.cargo/registry/src"
    ];
  };
}
