#!/usr/bin/env bash

set -euo pipefail

# updates single user $1
update_user() {
    local user="$1"

    local homeDir
    homeDir="$(eval echo "~$user")"

    # real lock file, used by nvim
    local real_lock_file="$homeDir/.config/nvim/lazy-lock.json"

    # local lock file, stored in config
    local local_lock_file="$PWD/lazy-lock/$user.json"

    if [ ! -e "$local_lock_file" ]; then
        touch "$local_lock_file"
    fi

    # make real_lock_file point to local_lock_file, not to readonly /nix/store
    if [ -e "$real_lock_file" ]; then
        unlink "$real_lock_file"
    fi

    ln -s "$local_lock_file" "$real_lock_file"

    # update lock file
    nvim \
        --headless \
        -c ':Lazy! sync' \
        -c ':Lazy! load nvim-treesitter' \
        -c ':TSInstallSync all' \
        -c ':TSUpdateSync' \
        -c qa

    # remove real_lock_file, so it could be created by home-manager
    unlink "$real_lock_file"
}
update_user_decl="$(declare -f update_user)"

update_all() {
    local users
    users=($(../../lsusers))

    for user in "${users[@]}"; do
        sudo -u "$user" bash -c "$update_user_decl; update_user ${user}"
    done
}

run() {
    cd "$(dirname "$0")"
    update_all
}

run
