require('map').setup() -- should be the first one `require`d
require('filetype').setup()
require('opt').setup()
require('looks').setup()
require('manipulation').setup()
require('navigation').setup()
require('treesitter').setup()
require('lsp').setup()
require('complete').setup()
require('format').setup()
